### ISSUE TITLE
OS license missing

### ISSUE THREAD

**Issue by sameerparekh** [scalamacros/resetallattrs#9]
Hello, we'd like to use this project internally, but since there is no open source license, we can't. Would you be willing to add an open source license to this code? Ideally one of the following licenses please:

- Academic Free License 3.0
- Apache Software License 2.0 (AL)
- Boost Software License Version 1.0
- BSD (variants)
- Eclipse Distribution License (EDL) 1.0
- GNU Free Documentation License 1.3
- ISC License (simplified BSD)
- MIT
- MS-PL
- NCSA
- Python Software Foundation License
- W3C Software License
- X.net
- zlib/libpng

Thanks!

**Comment by xeno-by** [comment]
I can license this under Scala License. Would that work for you?

**Comment by xeno-by** [comment]
@holograph What do you think about Scala License? Since you're a contributor, I can't decide this unilaterally.

**Comment by holograph** [comment]
@xeno-by I've always been a fan of the major FOSS licenses (APL, BSD, MIT), but in this case I guess the Scala license is equally valid.

**Comment by sameerparekh** [comment]
That would be great, thanks Eugene!

**Comment by xeno-by** [comment]
I've just added LICENSE.md to the root of the project. Sorry for taking so long to take care of that.
